# Generated by Django 4.2.7 on 2024-01-08 04:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the paint brand', null=True)),
                ('logo', models.ImageField(blank=True, help_text='Logo of the paint brand', null=True, upload_to='brand_logos/')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Oil Paint', 'Oil Paint'), ('Cement Paint', 'Cement Paint'), ('Distemper Paint', 'Distemper Paint'), ('Emulsion Paint', 'Emulsion Paint'), ('Whitewash', 'Whitewash'), ('Enamel Paint', 'Enamel Paint'), ('Acrylic Emulsion Paint', 'Acrylic Emulsion Paint'), ('Bituminous Paint', 'Bituminous Paint'), ('Synthetic Rubber Paint', 'Synthetic Rubber Paint'), ('Anti-Corrosion Paint', 'Anti-Corrosion Paint')], max_length=100)),
                ('color_code', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Color code must start with "#" and have exactly 6 characters following it.', regex='^#[0-9A-Fa-f]{6}$')])),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Inventory.brand')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=100)),
                ('supplier_phone_no', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be between 10 and 15 digits.', regex='^\\d{10,15}$')])),
                ('supplier_email', models.EmailField(max_length=254)),
                ('supplied_products', models.ManyToManyField(related_name='suppliers', to='Inventory.product')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('price', models.PositiveIntegerField()),
                ('alert_threshold', models.IntegerField(default=10, help_text='Set the alert threshold for low stock')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Inventory.product')),
            ],
        ),
    ]
